theme: jekyll-theme-dinky
title: Amirali Najafi
logo: "/amirali.jpg?raw=true"
description: >
  Ph.D. candidate at the Smart Structures Technology Laboratory at the University of Illinois at Urbana-Champaign
  <br>
