theme: jekyll-theme-minimal
title: Amirali Najafi
github:
  is_project_page: false
logo: "/amirali.jpg?raw=true"
description: >
  100 Brett Rd, Piscataway NJ<br>
  224 CAIT: Center for Advanced Infrastructure and Transportation at Rutgers<br>
  Email: amirali.najafi@rutgers.edu <br><br>
  <a href="https://www.linkedin.com/in/amirali-najafi-3894ab1b4/"> View My LinkedIn Profile</a>
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=kGZwM9QAAAAJ"> View My Google Scholar Profile</a>

