theme: jekyll-theme-minimal
title: Amirali Najafi
logo: "/amirali.jpg?raw=true"
description: >
  Ph.D. candidate at the <a href="https://sstl.cee.illinois.edu/"> Smart Structures Technology Laboratory</a> at the University of Illinois at Urbana-Champaign, working with <a href="https://cee.illinois.edu/professor-billie-f-spencer">Dr. Billie F. Spencer</a>.
  <br><br>
  <a href="https://www.linkedin.com/in/amirali-najafi-3894ab1b4/"> View My LinkedIn Profile</a>
  <br>
  <a href="https://scholar.google.com/citations?hl=en&user=kGZwM9QAAAAJ"> View My Google Scholar Profile</a>
  <br>
  <a href="https://www.researchgate.net/profile/Amirali_Najafi"> View My ResearchGate Profile</a>
